Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
