require:
  - rubocop-minitest
  - rubocop-rake

Rake/Desc:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

#
# enable so-called "pending cops"
# after "minor" RuboCop upgrades!
#
# https://docs.rubocop.org/en/latest/versioning/#pending-cops
#

AllCops:
  NewCops: enable
