#!/usr/bin/env ruby

require 'mkmf'
require 'English'
require 'fileutils'
require 'shellwords'
require 'io/console'

module Kernel
  def which(executable)
    MakeMakefile.find_executable0(executable)
  end

  def rlwrap_version
    `rlwrap --version`.chomp
  rescue Errno::ENOENT
    'rlwrap not installed'
  end
end

class String
  def colorize(color_code)
    "\e[#{color_code}m#{self}\e[0m"
  end

  def bold()   colorize('1'); end
  def invert() colorize('7'); end

  def red()   colorize('31'); end
  def blue()  colorize('34'); end
  def green() colorize('32'); end

  def true?
    self == 'true'
  end

  def comment?
    start_with? '#'
  end
end

if ARGV.delete('--version')
  IO.console.puts "repl 0.12.0 (#{rlwrap_version})"
  exit(0)
end

if ARGV.delete('--help') || ARGV.empty?
  IO.console.puts DATA.read
  exit(0)
end

if ARGV.delete('--html')
  exec "open #{File.join(__dir__, 'repl.1.html')}"
  exit(0) # superfluous, really...
end

if ARGV.delete('--man')
  exec "man #{File.join(__dir__, 'repl.1')}"
  exit(0) # superfluous, really...
end

# list of remaining options/flags
OPTIONS = %w[--stdin --printf --escape --debug --clear].freeze

unless ENV['__REPL_RLWRAP__']
  # merge "${HOME}/.repl.rc" into ENV
  if File.file? repl_rc = File.join(Dir.home, '.repl.rc')
    File.readlines(repl_rc).map(&:strip).each do |line|
      next if line.empty?
      next if line.comment?

      key, value = line.chomp.split('=')
      ENV[key] = value[1..-2] # strip double quotes
    end
  end

  # replace process with `rlwrap`-ed version
  if (rlwrap_exec = which('rlwrap'))
    rlwrap_args = []

    unless (base_cmd = (ARGV - OPTIONS).map(&:strip).first).empty?
      base_cmd = File.basename(base_cmd)

      default_history_dir = Dir.home
      history_dir = ENV['REPL_HISTORY_DIR'] || default_history_dir

      if File.directory? history_dir = File.expand_path(history_dir)
        history_file = File.join(history_dir, ".#{base_cmd}_history")
        rlwrap_args += ['-H', history_file]
      end

      default_completion_dir = File.join(Dir.home, '.repl')
      completion_dir = ENV['REPL_COMPLETION_DIR'] || default_completion_dir

      if File.directory? completion_dir = File.expand_path(completion_dir)
        completion_file = File.join(completion_dir, base_cmd)
        rlwrap_args += ['-f', completion_file] if File.exist? completion_file
      end
    end

    ENV['__REPL_RLWRAP__'] = Process.pid.to_s
    exec("#{rlwrap_exec} #{rlwrap_args.join(' ')} #{$PROGRAM_NAME} #{ARGV.join(' ')}")
  end
end

# process the options
stdin  = ARGV.delete('--stdin')
printf = ARGV.delete('--printf')
escape = ARGV.delete('--escape') || ENV['REPL_ESCAPE']&.true?
debug  = ARGV.delete('--debug') || ENV['REPL_DEBUG']&.true?
clear  = ARGV.delete('--clear') || ENV['REPL_CLEAR']&.true?

# command is whatever's left
if (cmd_string = ARGV.join(' ').strip).empty?
  IO.console.puts 'No command specified... use `--help`'
  exit(0)
end

cmd_template = if stdin
                 pipe_cmd = which(printf ? 'printf' : 'echo')
                 "#{pipe_cmd} \"%s\" | #{cmd_string}"
               elsif ARGV.grep(/%s/).any?
                 cmd_string # the '%s' is embedded
               else
                 "#{cmd_string} %s"
               end

default_prompt = debug ? cmd_template : cmd_string
default_prompt = default_prompt.bold
default_prompt = "#{default_prompt} >>".freeze

repl_prompt = "#{ENV.fetch('REPL_PROMPT', default_prompt)} "

loop do
  IO.console.print repl_prompt

  line = begin
    $stdin.gets&.strip
  rescue Interrupt
    nil
  end

  break unless line

  line = Shellwords.escape(line) if escape
  # command = format(cmd_template, line)  # expand single '%s' placeholder
  command = cmd_template.gsub('%s', line) # expand _all_ '%s' placeholders

  IO.console.puts "\e[H\e[2J"    if clear
  IO.console.puts "$ #{command}" if debug

  begin
    system(command, exception: true)
  rescue RuntimeError, Errno::ENOENT
    IO.console.print 'system(\'', command.blue, '\'): '
    IO.console.puts $ERROR_INFO.message.red
  end
  IO.console.puts # empty separator line
end

exit(0) # cleanly exit repl

__END__
Usage: repl [options] command ...

Options:
  --version Display the repl version
  --help    Display this message
  --man     Display the man page
  --html    Open HTML version of man page
  --stdin   Pipe input to command's STDIN
  --printf  Avoid newline chars in STDIN
  --escape  Shell escape user's input
  --debug   Display each command executed
  --clear   Clear terminal after each command

Homepage:

  http://github.com/pvdb/repl

Bug reports, suggestions, updates:

  http://github.com/pvdb/repl/issues

That's all Folks!
