#!/usr/bin/env ruby
# frozen_string_literal: true

REPL_NAME = 'repl'
REPL_VERSION = '1.0.0' # match with `lib/repl/version.rb`

require 'mkmf'
require 'English'
require 'fileutils'
require 'shellwords'
require 'io/console'

##
# script-specific Kernel extension
module Kernel
  def which(executable)
    MakeMakefile.find_executable0(executable)
  end
end

##
# script-specific String extensions
class String
  def colorize(color_code)
    "\e[#{color_code}m#{self}\e[0m"
  end

  # rubocop:disable Style/SingleLineMethods
  def bold()   colorize('1'); end
  def invert() colorize('7'); end

  def red()   colorize('31'); end
  def blue()  colorize('34'); end
  def green() colorize('32'); end
  # rubocop:enable Style/SingleLineMethods

  def true?
    self == 'true'
  end

  def comment?
    start_with? '#'
  end
end

##
# version of rlwrap utility
def rlwrap_version
  `rlwrap --version`.chomp
rescue Errno::ENOENT
  'rlwrap not installed'
end

##
# version of repl script
def repl_version
  "#{REPL_NAME} #{REPL_VERSION} (#{rlwrap_version})"
end

if ARGV.delete('--version')
  IO.console.puts repl_version
  exit(0)
end

if ARGV.delete('--help')
  IO.console.puts DATA.read
  exit(0)
end

if ARGV.delete('--man')
  exec "man #{File.join(__dir__, 'repl.1')}"
  exit(0) # superfluous, really...
end

if ARGV.delete('--html')
  exec "open #{File.join(__dir__, 'repl.1.html')}"
  exit(0) # superfluous, really...
end

# list of remaining options/flags
OPTIONS = %w[--stdin --printf --escape --debug --clear --quiet].freeze

##
# is repl running "inside" rlwrap?
def repl_wrapped?
  !ENV['__REPL_RLWRAP__'].nil?
end

unless repl_wrapped?
  # merge "${HOME}/.repl.rc" into ENV
  if File.file? repl_rc = File.join(Dir.home, '.repl.rc')
    File.readlines(repl_rc, chomp: true).each do |line|
      next if line.empty?
      next if line.comment?

      key, value = line.split(/\s*=\s*/, 2).map(&:strip)

      # strip surrounding quotes
      value.delete_prefix!('"')
      value.delete_suffix!('"')

      ENV[key] = value
    end
  end

  # replace process with `rlwrap`-ed version
  if (rlwrap_exec = which('rlwrap'))
    rlwrap_args = []

    # rubocop:disable Metrics/BlockNesting
    # rubocop:disable Style/SoleNestedConditional
    unless (base_cmd = (ARGV - OPTIONS).map(&:strip).first).nil?
      unless which(base_cmd).nil?
        base_cmd = File.basename(base_cmd)

        default_history_dir = Dir.home
        history_dir = ENV['REPL_HISTORY_DIR'] || default_history_dir

        if File.directory? history_dir = File.expand_path(history_dir)
          history_file = File.join(history_dir, ".#{base_cmd}_history")
          rlwrap_args += ['-H', history_file]
        end

        default_completion_dir = File.join(Dir.home, '.repl')
        completion_dir = ENV['REPL_COMPLETION_DIR'] || default_completion_dir

        if File.directory? completion_dir = File.expand_path(completion_dir)
          if File.exist? completion_file = File.join(completion_dir, base_cmd)
            rlwrap_args += ['-f', completion_file]
          end
        end
      end
    end
    # rubocop:enable Style/SoleNestedConditional
    # rubocop:enable Metrics/BlockNesting

    ENV['__REPL_RLWRAP__'] = Process.pid.to_s

    repl_wrapped = "#{rlwrap_exec} #{rlwrap_args.join(' ')} #{$PROGRAM_NAME} #{ARGV.join(' ')}"

    exec(repl_wrapped)
  end
end

# process the options
stdin  = ARGV.delete('--stdin')
printf = ARGV.delete('--printf')
escape = ARGV.delete('--escape') || ENV['REPL_ESCAPE']&.true?
debug  = ARGV.delete('--debug') || ENV['REPL_DEBUG']&.true?
clear  = ARGV.delete('--clear') || ENV['REPL_CLEAR']&.true?
quiet  = ARGV.delete('--quiet') || ENV['REPL_QUIET']&.true?

# command is whatever's left
if (cmd_string = ARGV.join(' ').strip).empty?
  IO.console.puts 'No command specified... use `--help`'
  exit(0)
end

cmd_template = if stdin
                 pipe_cmd = which(printf ? 'printf' : 'echo')
                 "#{pipe_cmd} \"%s\" | #{cmd_string}"
               elsif ARGV.grep(/%s/).any?
                 cmd_string # the '%s' is embedded
               else
                 "#{cmd_string} %s"
               end

cmd_prompt = if debug
               if repl_wrapped?
                 "rlwrap(repl(\"#{cmd_template.blue}\"))"
               else
                 "repl(\"#{cmd_template.blue}\")"
               end
             else
               "\"#{cmd_template.blue}\""
             end

repl_prompt = ENV.fetch('REPL_PROMPT', '>>')
repl_prompt = "#{cmd_prompt} #{repl_prompt}"

loop do
  # prompt user for cmd arguments
  IO.console.print(repl_prompt, ' ') if $stdin.tty? || !quiet

  line = begin
    $stdin.gets&.strip # nil when ^D
  rescue Interrupt
    nil # Interrupt is raised for ^C
  end

  # echo input if read from stdin pipe
  IO.console.puts(line) unless $stdin.tty? || quiet

  break unless line # ^C / ^D / EOF

  line = Shellwords.escape(line) if escape

  # command = format(cmd_template, line)  # expand single '%s' placeholder
  command = cmd_template.gsub('%s', line) # expand _all_ '%s' placeholders

  IO.console.puts "\e[H\e[2J"    if clear
  IO.console.puts "$ #{command}" if debug

  begin
    system(command, exception: true)
  rescue RuntimeError, Errno::ENOENT
    IO.console.print 'system("', command.blue, '"): '
    IO.console.puts $ERROR_INFO.message.red
  end

  # empty separator line
  IO.console.puts
end

exit(0) # cleanly exit repl

__END__
Usage: repl [options] command ...

Options:
  --version Display the repl version
  --help    Display this message
  --man     Display the man page
  --html    Open HTML version of man page
  --stdin   Pipe input to command's STDIN
  --printf  Avoid newline chars in STDIN
  --escape  Shell escape user's input
  --debug   Display each command executed
  --clear   Clear terminal after each command
  --quiet   Don't echo the prompt in pipelines

Homepage:

  http://github.com/pvdb/repl

Bug reports, suggestions, updates:

  http://github.com/pvdb/repl/issues

That's all Folks!
