#!/usr/bin/env ruby

lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'repl'

if ARGV.delete('--help') || ARGV.empty?
  puts File.read(File.join(__dir__, '..', 'man', 'repl.txt'))
  exit(0)
end

if ARGV.delete('--version')
  puts Repl::VERSION
  exit(0)
end

if ARGV.delete('--man')
  exec "man #{File.join(__dir__, '..', 'man', 'repl.1')}"
  exit(0) # superfluous, really...
end

# list of options/flags
OPTIONS = %w{--clear --debug --stdin --escape}.freeze

if MakeMakefile.find_executable0('rlwrap')
  unless ENV['__REPL_RLWRAP__']
    rlwrap_args = []

    unless (base_cmd = (ARGV - OPTIONS).map(&:strip).first).empty?
      base_cmd = File.basename(base_cmd)

      default_history_dir = Dir.home
      history_dir = ENV['REPL_HISTORY_DIR'] || default_history_dir

      if File.directory? history_dir = File.expand_path(history_dir)
        history_file = File.join(history_dir, ".#{base_cmd}_history")
        rlwrap_args += ['-H', history_file]
      end

      default_completion_dir = File.join(Dir.home, '.repl')
      completion_dir = ENV['REPL_COMPLETION_DIR'] || default_completion_dir

      if File.directory? completion_dir = File.expand_path(completion_dir)
        completion_file = File.join(completion_dir, base_cmd)
        rlwrap_args += ['-f', completion_file] if File.exist? completion_file
      end
    end

    ENV['__REPL_RLWRAP__'] = Process.pid.to_s
    exec("rlwrap #{rlwrap_args.join(' ')} #{$PROGRAM_NAME} #{ARGV.join(' ')}")
  end
end

# process the options
clear  = ARGV.delete('--clear')
debug  = ARGV.delete('--debug')
stdin  = ARGV.delete('--stdin')
escape = ARGV.delete('--escape')

# command is whatever's left
cmd_parts  = ARGV.map(&:strip)
embed      = cmd_parts.grep(/%s/).any?
cmd_string = cmd_parts.join(' ').strip

if cmd_string.empty?
  puts 'No command specified... use `--help`'
  exit(0)
end

cmd_template = if stdin
                 "/bin/echo -n \"%s\" | #{cmd_string}"
               elsif embed
                 cmd_string # the '%s' is embedded
               else
                 "#{cmd_string} %s"
               end

cmd_prompt = (debug ? cmd_template : cmd_string).bold

loop do
  print cmd_prompt
  print ' >> '

  line = begin
           $stdin.gets&.strip
         rescue Interrupt
           nil
         end

  exit(0) unless line

  line = Shellwords.escape(line) if escape
  command = format(cmd_template, line)

  puts "\e[H\e[2J"    if clear
  puts "$ #{command}" if debug

  system(command)
  puts # empty separator line
end

# That's all Folks!
