#!/usr/bin/env ruby

require 'mkmf'
require 'fileutils'
require 'shellwords'
require 'io/console'

if ARGV.delete('--version')
  IO.console.puts Repl::VERSION
  exit(0)
end

if ARGV.delete('--help') || ARGV.empty?
  IO.console.puts File.read(File.join(__dir__, '..', 'man', 'repl.txt'))
  exit(0)
end

if ARGV.delete('--man')
  exec "man #{File.join(__dir__, '..', 'man', 'repl.1')}"
  exit(0) # superfluous, really...
end

# list of remaining options/flags
OPTIONS = %w[--stdin --escape --printf --debug --clear].freeze

if MakeMakefile.find_executable0('rlwrap')
  unless ENV['__REPL_RLWRAP__']
    rlwrap_args = []

    unless (base_cmd = (ARGV - OPTIONS).map(&:strip).first).empty?
      base_cmd = File.basename(base_cmd)

      default_history_dir = Dir.home
      history_dir = ENV['REPL_HISTORY_DIR'] || default_history_dir

      if File.directory? history_dir = File.expand_path(history_dir)
        history_file = File.join(history_dir, ".#{base_cmd}_history")
        rlwrap_args += ['-H', history_file]
      end

      default_completion_dir = File.join(Dir.home, '.repl')
      completion_dir = ENV['REPL_COMPLETION_DIR'] || default_completion_dir

      if File.directory? completion_dir = File.expand_path(completion_dir)
        completion_file = File.join(completion_dir, base_cmd)
        rlwrap_args += ['-f', completion_file] if File.exist? completion_file
      end
    end

    ENV['__REPL_RLWRAP__'] = Process.pid.to_s
    exec("rlwrap #{rlwrap_args.join(' ')} #{$PROGRAM_NAME} #{ARGV.join(' ')}")
  end
end

class String
  def colorize(color_code)
    "\e[#{color_code}m#{self}\e[0m"
  end
end

# process the options
stdin  = ARGV.delete('--stdin')
escape = ARGV.delete('--escape')
printf = ARGV.delete('--printf')
debug  = ARGV.delete('--debug')
clear  = ARGV.delete('--clear')

# command is whatever's left
if (cmd_string = ARGV.join(' ').strip).empty?
  IO.console.puts 'No command specified... use `--help`'
  exit(0)
end

cmd_template = if stdin
                 pipe_cmd = printf ? '/usr/bin/printf' : '/bin/echo'
                 "#{pipe_cmd} \"%s\" | #{cmd_string}"
               elsif ARGV.grep(/%s/).any?
                 cmd_string # the '%s' is embedded
               else
                 "#{cmd_string} %s"
               end

cmd_prompt = (debug ? cmd_template : cmd_string).colorize(1) # bold

loop do
  IO.console.print cmd_prompt
  IO.console.print ' >> '

  line = begin
    $stdin.gets&.strip
  rescue Interrupt
    nil
  end

  break unless line

  line = Shellwords.escape(line) if escape
  # command = format(cmd_template, line)  # expand single '%s' placeholder
  command = cmd_template.gsub('%s', line) # expand _all_ '%s' placeholders

  IO.console.puts "\e[H\e[2J"    if clear
  IO.console.puts "$ #{command}" if debug

  if system(command).nil?
    IO.console.print 'system("', command, '"): ' unless debug
    IO.console.puts '<Errno::ENOENT>'.red
  end
  IO.console.puts # empty separator line
end

# That's all Folks!
